services:
  app:
    image: ghcr.io/modest-human-brands/modest-human-brands:latest
    env_file:
      - .env
    volumes:
      - modest-human-brands_data:/app/.data
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - connect
      - doc
      - drive
      - media
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  connect:
    image: ghcr.io/modest-human-brands/mconnect:latest
    env_file:
      - .env
    volumes:
      - mconnect-config:/app/config
      - mconnect-data:/app/.data
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - connect-livekit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  connect-livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    # ports:
    #   - "7881:7881/tcp"
    #   - "7882:7882/udp"
    #   - "50000-60000:50000-60000/udp"
    volumes:
      - /root/modest-human-brands/mconnect/config/livekit.yaml:/etc/livekit.yaml
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:7880/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  connect-livekit-egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - /root/modest-human-brands/mconnect/config/egress.yaml:/etc/egress.yaml
      - /root/modest-human-brands/mconnect/recordings:/recordings
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:7980/ || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    depends_on:
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  connect-livekit-sip:
    image: livekit/sip:latest
    ports:
      - '5060:5060/udp'
      - '5060:5060/tcp'
      - '10000-10100:10000-10100/udp'
    volumes:
      - /root/modest-human-brands/mconnect/config/sip.yaml:/sip/config.yaml
    networks:
      - internal
    # healthcheck:
    #   test: [ "CMD-SHELL", "exec 6<>/dev/tcp/localhost/5060 || exit 1" ]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
    depends_on:
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  connect-livekit-redis:
    image: redis:7-alpine
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  doc:
    image: ghcr.io/modest-human-brands/mdoc:latest
    env_file:
      - .env
    volumes:
      - mdoc-asset:/app/asset
      - mdoc-document:/app/document
      - mdoc-static:/app/static
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  drive:
    image: ghcr.io/modest-human-brands/mdrive:latest
    env_file:
      - .env
    volumes:
      - mdrive-data:/app/.data
      - mdrive-static:/app/static
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  media:
    image: ghcr.io/modest-human-brands/mmedia:latest
    env_file:
      - .env
    volumes:
      - mdrive-static:/app/static
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://127.0.0.1:3111/health || exit 1']
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

volumes:
  modest-human-brands_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/.data
  mconnect-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mconnect/config
  mconnect-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mconnect/.data
  mdoc-asset:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdoc/asset
  mdoc-document:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdoc/document
  mdoc-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdoc/static
  mdrive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/.data
  mdrive-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/static

networks:
  internal:
    driver: overlay
