services:
  app:
    image: ghcr.io/modest-human-brands/modest-human-brands:latest
    env_file:
      - .env
    volumes:
      - modest-human-brands_data:/app/.data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect:
    image: ghcr.io/modest-human-brands/mconnect:latest
    env_file:
      - .env
    volumes:
      - /root/modest-human-brands/mconnect/config:/app/config
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect-livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    # ports:
    #   - "7881:7881/tcp"
    #   - "7882:7882/udp"
    #   - "50000-60000:50000-60000/udp"
    volumes:
      - /root/modest-human-brands/mconnect/config/livekit.yaml:/etc/livekit.yaml
    networks:
      - internal
    depends_on:
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect-livekit-egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - /root/modest-human-brands/mconnect/config/egress.yaml:/etc/egress.yaml
      - /root/modest-human-brands/mconnect/recordings:/recordings
    networks:
      - internal
    depends_on:
      - connect-livekit
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect-livekit-sip:
    image: livekit/sip:latest
    ports:
      - '5060:5060/udp'
      - '5060:5060/tcp'
      - '10000-10100:10000-10100/udp'
    volumes:
      - /root/modest-human-brands/mconnect/config/sip.yaml:/sip/config.yaml
    networks:
      - internal
    depends_on:
      - connect-livekit
      - connect-livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect-livekit-redis:
    image: redis:7-alpine
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  doc:
    image: ghcr.io/modest-human-brands/mdoc:latest
    env_file:
      - .env
    volumes:
      - mdoc-document:/app/document
      - mdoc-static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  drive:
    image: ghcr.io/modest-human-brands/mdrive:latest
    env_file:
      - .env
    volumes:
      - mdrive-data:/app/data
      - mdrive-static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  media:
    image: ghcr.io/modest-human-brands/mmedia:latest
    env_file:
      - .env
    volumes:
      - mdrive-static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

volumes:
  modest-human-brands_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/.data
  mconnect-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mconnect/config
  mdoc-document:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdoc/document
  mdoc-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdoc/static
  mdrive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/data
  mdrive-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/static

networks:
  internal:
    driver: overlay
