services:
  app:
    image: ghcr.io/modest-human-brands/modest-human-brands:latest
    env_file:
      - .env
    volumes:
      - modest-human-brands_data:/app/.data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  connect:
    image: ghcr.io/modest-human-brands/mconnect:latest
    env_file:
      - .env
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  doc:
    image: ghcr.io/modest-human-brands/mdoc:latest
    env_file:
      - .env
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  drive:
    image: ghcr.io/modest-human-brands/mdrive:latest
    env_file:
      - .env
    volumes:
      - mdrive-data:/app/data
      - mdrive-static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  media:
    image: ghcr.io/modest-human-brands/mmedia:latest
    env_file:
      - .env
    volumes:
      - mdrive-static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

  ome:
    image: airensoft/ovenmediaengine:latest
    expose:
      - '3333' #
      - '3334'
      - '3480' # LLHSL playback
      - '8080' # HLS/DASH playback
      - '8081' # REST API
    ports:
      - '3478:3478' # TURN TCP relay (fixed mapping)
      - '9999:9999/udp' # SRT ingest
      - '10000:10000/udp' # ICE media
      - '10001:10001/udp'
      - '10002:10002/udp'
      - '10003:10003/udp'
      - '10004:10004/udp'
      - '10005:10005/udp'
    env_file:
      - .env
    volumes:
      - /root/modest-human-brands/ome/ome.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml
      - /root/modest-human-brands/ome/omeRecord.xml:/opt/ovenmediaengine/bin/origin_conf/record_map.xml
      - mdrive-static:/opt/ovenmediaengine/media
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  modest-human-brands_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/.data
  mdrive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/data
  mdrive-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/modest-human-brands/mdrive/static

networks:
  internal:
    driver: overlay
