services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - NITRO_PUBLIC_DOC_URL=http://doc:3000
    volumes:
      - modest-human-brands_data:/app/.data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 3000:3000

  connect:
    image: ghcr.io/modest-human-brands/mconnect:latest
    env_file:
      - .env
    volumes:
      - mconnect-config:/app/config
      - mconnect-data:/app/.data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 5100:3000

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    # ports:
    #   - "7881:7881/tcp"
    #   - "7882:7882/udp"
    #   - "50000-60000:50000-60000/udp"
    volumes:
      - /root/modest-human-brands/mconnect/config/livekit.yaml:/etc/livekit.yaml
    depends_on:
      - livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  livekit-egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - /root/modest-human-brands/mconnect/config/egress.yaml:/etc/egress.yaml
      - /root/modest-human-brands/mconnect/recordings:/recordings
    depends_on:
      - livekit
      - livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  livekit-sip:
    image: livekit/sip:latest
    ports:
      - '5060:5060/udp'
      - '5060:5060/tcp'
      - '10000-10100:10000-10100/udp'
    volumes:
      - /root/modest-human-brands/mconnect/config/sip.yaml:/sip/config.yaml
    depends_on:
      - livekit
      - livekit-redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  livekit-redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  doc:
    build: ../code-doc
    env_file:
      - .env
    volumes:
      - mdoc-asset:/app/asset
      - mdoc-document:/app/document
      - mdoc-static:/app/static
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 3002:3000

  drive:
    image: ghcr.io/modest-human-brands/mdrive:latest
    env_file:
      - .env
    volumes:
      - mdrive-data:/app/data
      - mdrive-static:/app/static
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  media:
    image: ghcr.io/modest-human-brands/mmedia:latest
    env_file:
      - .env
    volumes:
      - mdrive-static:/app/static
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

volumes:
  modest-human-brands_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data

  mconnect-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mconnect/config
  mconnect-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mconnect/.data

  mdoc-asset:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../code-doc/asset
  mdoc-document:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../code-doc/document
  mdoc-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../code-doc/static

  mdrive-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mdrive/data
  mdrive-static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mdrive/static
